
message(STATUS "Use GCC toolchain install dir: " ${CMSDK_LOCAL_PATH})
set(CMAKE_INSTALL_PREFIX ${CMSDK_LOCAL_PATH} CACHE INTERNAL "CLANG INSTALL PREFIX")
include_directories(SYSTEM ${CMSDK_LOCAL_PATH}/include)

set(CMSDK_SDK_IS_WINDOWS TRUE CACHE INTERNAL "WINDOWS BUILD")
set(CMAKE_C_FLAGS "-D__win32 -mno-ms-bitfields -D__processor_${CMAKE_HOST_SYSTEM_PROCESSOR}" CACHE INTERNAL "MINGW C FLAGS")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}" CACHE INTERNAL "CLANG CXX FLAGS")
