
message(STATUS "Use Clang toolchain install dir: " ${CMSDK_LOCAL_PATH})
set(CMAKE_INSTALL_PREFIX ${CMSDK_LOCAL_PATH} CACHE INTERNAL "CLANG INSTALL PREFIX")
include_directories(SYSTEM ${CMSDK_LOCAL_PATH}/include)

set(CMSDK_SDK_IS_LINUX TRUE CACHE INTERNAL "LINUX BUILD")
set(TOOLCHAIN_C_FLAGS "-D__linux -D__processor_${CMAKE_HOST_SYSTEM_PROCESSOR}" CACHE INTERNAL "CLANG C FLAGS")
set(TOOLCHAIN_CXX_FLAGS "${TOOLCHAIN_C_FLAGS}" CACHE INTERNAL "CLANG CXX FLAGS")

set(CMAKE_C_FLAGS "${TOOLCHAIN_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${TOOLCHAIN_CXX_FLAGS}")


